name: Automated Security Scan (Bandit)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast-scan:
    name: Static Application Security Testing
    runs-on: ubuntu-latest

    steps:
    # Updated to v4
    - name: Checkout Code
      uses: actions/checkout@v4

    # Updated to v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask bandit

    - name: Run Bandit Scan
      run: |
        bandit -r app.py -f txt -o bandit_report_cicd.txt || true

    # Updated to v4 (This fixes your error!)
    - name: Upload Vulnerability Report
      uses: actions/upload-artifact@v4
      with:
        name: Bandit-Security-Report
        path: bandit_report_cicd.txt